### ISSUE TITLE
No Previews 

### ISSUE THREAD

**Issue by AhmedHaroon07** [saadali05/Landing-page#1]
**### PREVIEW KAHAN HAI!**

Adding a preview of your Landing Page with the markdown file would be great because in order to run or preview i had to download all the assets which is not optimal
and yeah i've also used the **SEND A MESSAGE** feature XD

**Comment by saadkhi** [comment]
I'm sorry, I forgot to provide website URL in the Readme file or in description. This is the link of the website: (https://saadali05.github.io/Landing-page/). Here You can review my portfolio (website).
